# Generated by Django 2.0.5 on 2020-05-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='category',
            new_name='categoria',
        ),
    ]
