# Generated by Django 2.0.5 on 2020-05-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20200510_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nombre',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
